# Generated by Django 5.0 on 2024-01-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Creation_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=225)),
                ('Category', models.CharField(choices=[('H', 'Home'), ('S', 'School'), ('O', 'Office')], max_length=1)),
                ('description', models.TextField()),
            ],
        ),
    ]
