# Generated by Django 5.0 on 2024-01-28 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0002_remove_task_creation_date_task_creation_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Category',
            new_name='category',
        ),
    ]
