# Generated by Django 5.0 on 2024-01-29 17:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0006_task_model_delete_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='task_model',
            new_name='Task',
        ),
    ]
