# Generated by Django 5.0 on 2024-01-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0008_alter_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_number',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
    ]
